import { getArticles } from "@/lib/data/articles";
import { getTemplate } from "@/lib/data/templates";
import type { Edition, EditionBlock, Metric, Template } from "@/lib/types";

/**
 * Generated editions. A briefing's edition is the actual intelligence product:
 * the structure comes from the template, the content from the briefing's
 * instructions. Everything here is deterministic mock output.
 */

const METRICS_EXEC: Metric[] = [
  {
    id: "m-volume",
    label: "Total mentions",
    value: "1,284",
    delta: "+18%",
    direction: "up",
    positiveIsGood: true,
  },
  {
    id: "m-sentiment",
    label: "Positive sentiment",
    value: "62%",
    delta: "+7 pts",
    direction: "up",
    positiveIsGood: true,
  },
  {
    id: "m-tier1",
    label: "Tier 1 share",
    value: "31%",
    delta: "+4 pts",
    direction: "up",
    positiveIsGood: true,
  },
  {
    id: "m-risk",
    label: "Negative mentions",
    value: "146",
    delta: "+23%",
    direction: "up",
    positiveIsGood: false,
  },
];

const COVERAGE_TREND = [
  { label: "Mon", value: 142, negative: 18 },
  { label: "Tue", value: 168, negative: 21 },
  { label: "Wed", value: 154, negative: 16 },
  { label: "Thu", value: 211, negative: 34 },
  { label: "Fri", value: 248, negative: 29 },
  { label: "Sat", value: 96, negative: 11 },
  { label: "Sun", value: 88, negative: 9 },
];

/* -------------------------------------------------------------------------- */
/* Morning Intelligence Brief — the hero edition                               */
/* -------------------------------------------------------------------------- */

const MORNING_BLOCKS: EditionBlock[] = [
  {
    id: "b-banner",
    kind: "banner",
    title: "Morning Intelligence Brief",
    subtitle: "Global Communications",
  },
  {
    id: "b-contents",
    kind: "contents",
    entries: [
      { id: "sec-top-stories", title: "Top Stories" },
      { id: "sec-policy", title: "Policy & Access" },
      { id: "sec-competitive", title: "Competitive Watch" },
    ],
  },
  {
    id: "b-s1-title",
    kind: "sectionTitle",
    title: "Top Stories",
    sectionId: "sec-top-stories",
  },
  {
    id: "b-s1-summary",
    kind: "summary",
    sectionId: "sec-top-stories",
    text: "The quarter's revenue beat is carrying the news cycle and has pushed the patent-cliff frame off the front of most coverage. The Phase III readout gives that story a second day of legs. Against it, respiratory vaccine uptake is tracking meaningfully below last season — the one number that complicates an otherwise strong morning.",
  },
  {
    id: "b-s1-stories",
    kind: "stories",
    sectionId: "sec-top-stories",
    articles: getArticles([
      "art-q2-revenue",
      "art-oncology-pipeline",
      "art-vaccine-uptake",
    ]),
  },
  {
    id: "b-s2-title",
    kind: "sectionTitle",
    title: "Policy & Access",
    sectionId: "sec-policy",
  },
  {
    id: "b-s2-summary",
    kind: "summary",
    sectionId: "sec-policy",
    text: "Two live deadlines this week. The Senate pricing hearing is now on the calendar for late September and witness invitations have not been made public — confirm our status before Thursday's edition. The EU accelerated access consultation closes in November and is, on balance, favourable to two of our rare disease programmes.",
  },
  {
    id: "b-s2-callout",
    kind: "callout",
    tone: "risk",
    sectionId: "sec-policy",
    title: "Watch item",
    text: "If a witness invitation lands, we need an agreed list-price position within 48 hours. Government affairs is confirming status today.",
  },
  {
    id: "b-s2-stories",
    kind: "stories",
    sectionId: "sec-policy",
    articles: getArticles([
      "art-pricing-hearing",
      "art-eu-access",
      "art-medicare-negotiation",
    ]),
  },
  {
    id: "b-s3-title",
    kind: "sectionTitle",
    title: "Competitive Watch",
    sectionId: "sec-competitive",
  },
  {
    id: "b-s3-summary",
    kind: "summary",
    sectionId: "sec-competitive",
    text: "The direct-to-patient distribution announcement is the move that matters. It reframes affordability on a competitor's terms and it will produce \u201cwhy not you\u201d questions inside two days. The halted obesity trial cuts the other way but is not worth commenting on — engaging invites the comparison we would rather avoid.",
  },
  {
    id: "b-s3-stories",
    kind: "stories",
    sectionId: "sec-competitive",
    articles: getArticles(["art-competitor-launch", "art-competitor-trial"]),
  },
  {
    id: "b-footer",
    kind: "footer",
    text: "Generated by Herald for Pfizer Global Communications. Coverage sourced from Handraise media intelligence.",
  },
];

/* -------------------------------------------------------------------------- */
/* Executive Coverage Summary                                                  */
/* -------------------------------------------------------------------------- */

const EXEC_BLOCKS: EditionBlock[] = [
  {
    id: "e-banner",
    kind: "banner",
    title: "Executive Coverage Summary",
    subtitle: "Leadership Distribution",
  },
  {
    id: "e-contents",
    kind: "contents",
    entries: [
      { id: "sec-headline", title: "The Headline" },
      { id: "sec-numbers", title: "Coverage at a Glance" },
      { id: "sec-stories-exec", title: "Stories to Know" },
    ],
  },
  {
    id: "e-h-title",
    kind: "sectionTitle",
    title: "The Headline",
    sectionId: "sec-headline",
  },
  {
    id: "e-h-summary",
    kind: "summary",
    sectionId: "sec-headline",
    text: "A strong week on execution: the revenue beat and the early Phase III readout together produced the highest positive share of voice we have recorded this year. The offsetting story is a competitor's direct-to-patient distribution launch, which moves the affordability conversation onto their framing. The week's real risk is not any single story but the pricing hearing now scheduled for late September.",
  },
  {
    id: "e-h-callout",
    kind: "callout",
    tone: "opportunity",
    sectionId: "sec-headline",
    title: "The one thing to act on",
    text: "The North Carolina manufacturing expansion is the strongest domestic-investment proof point we hold. Pairing it with any pricing question is the highest-leverage move available before the hearing.",
  },
  {
    id: "e-n-title",
    kind: "sectionTitle",
    title: "Coverage at a Glance",
    sectionId: "sec-numbers",
  },
  {
    id: "e-n-metrics",
    kind: "metrics",
    sectionId: "sec-numbers",
    metrics: METRICS_EXEC,
  },
  {
    id: "e-n-chart",
    kind: "lineChart",
    sectionId: "sec-numbers",
    title: "Coverage volume, last 7 days",
    points: COVERAGE_TREND,
  },
  {
    id: "e-s-title",
    kind: "sectionTitle",
    title: "Stories to Know",
    sectionId: "sec-stories-exec",
  },
  {
    id: "e-s-stories",
    kind: "stories",
    sectionId: "sec-stories-exec",
    articles: getArticles([
      "art-q2-revenue",
      "art-competitor-launch",
      "art-manufacturing",
    ]),
  },
  {
    id: "e-footer",
    kind: "footer",
    text: "Generated by Herald for Pfizer Global Communications. Coverage sourced from Handraise media intelligence.",
  },
];

/* -------------------------------------------------------------------------- */
/* Competitive Intelligence Weekly                                             */
/* -------------------------------------------------------------------------- */

const COMPETITIVE_BLOCKS: EditionBlock[] = [
  {
    id: "c-banner",
    kind: "banner",
    title: "Competitive Intelligence Weekly",
    subtitle: "EMEA Communications",
  },
  {
    id: "c-contents",
    kind: "contents",
    entries: [
      { id: "sec-sov", title: "Share of Voice" },
      { id: "sec-moves", title: "Competitor Moves" },
      { id: "sec-implications", title: "What It Means" },
    ],
  },
  {
    id: "c-sov-title",
    kind: "sectionTitle",
    title: "Share of Voice",
    sectionId: "sec-sov",
  },
  {
    id: "c-sov-pie",
    kind: "pieChart",
    sectionId: "sec-sov",
    title: "Category share of voice, last 7 days",
    points: [
      { label: "Pfizer", value: 34 },
      { label: "Competitor A", value: 27 },
      { label: "Competitor B", value: 21 },
      { label: "Competitor C", value: 11 },
      { label: "Others", value: 7 },
    ],
  },
  {
    id: "c-sov-summary",
    kind: "summary",
    sectionId: "sec-sov",
    text: "We hold 34% of category voice this week, up four points and the first time we have led the category since June. The gain is earnings-driven rather than structural — Competitor A's distribution announcement landed late in the window and its full effect will show in next week's split.",
  },
  {
    id: "c-m-title",
    kind: "sectionTitle",
    title: "Competitor Moves",
    sectionId: "sec-moves",
  },
  {
    id: "c-m-table",
    kind: "table",
    sectionId: "sec-moves",
    columns: ["Competitor", "Move", "Category", "Read"],
    rows: [
      {
        cells: [
          "Competitor A",
          "Direct-to-patient distribution",
          "Cardiometabolic",
          "Engage",
        ],
      },
      {
        cells: ["Competitor B", "Mid-stage trial halt", "Obesity", "Monitor"],
      },
      {
        cells: [
          "Competitor C",
          "Biosimilar approval, 2 EU markets",
          "Immunology",
          "Monitor",
        ],
      },
    ],
  },
  {
    id: "c-m-stories",
    kind: "stories",
    sectionId: "sec-moves",
    articles: getArticles([
      "art-competitor-launch",
      "art-biosimilar",
      "art-competitor-trial",
    ]),
  },
  {
    id: "c-i-title",
    kind: "sectionTitle",
    title: "What It Means",
    sectionId: "sec-implications",
  },
  {
    id: "c-i-summary",
    kind: "summary",
    sectionId: "sec-implications",
    text: "One move needs a response and two do not. Competitor A has made affordability a distribution question rather than a pricing question, and that is a frame we can answer with the patient assistance redesign already in flight. The biosimilar approval and the halted trial are both monitor-only: commenting on either invites a comparison that costs more than the coverage is worth.",
  },
  {
    id: "c-footer",
    kind: "footer",
    text: "Generated by Herald for Pfizer EMEA Communications. Coverage sourced from Handraise media intelligence.",
  },
];

/* -------------------------------------------------------------------------- */
/* Media Coverage Report                                                       */
/* -------------------------------------------------------------------------- */

const REPORT_BLOCKS: EditionBlock[] = [
  {
    id: "r-banner",
    kind: "banner",
    title: "Media Coverage Report",
    subtitle: "Corporate Reputation",
  },
  {
    id: "r-contents",
    kind: "contents",
    entries: [
      { id: "sec-performance", title: "Coverage Performance" },
      { id: "sec-themes", title: "Narrative Themes" },
      { id: "sec-top-coverage", title: "Top Coverage" },
    ],
  },
  {
    id: "r-p-title",
    kind: "sectionTitle",
    title: "Coverage Performance",
    sectionId: "sec-performance",
  },
  {
    id: "r-p-metrics",
    kind: "metrics",
    sectionId: "sec-performance",
    metrics: [
      {
        id: "rm-1",
        label: "Total placements",
        value: "1,107",
        delta: "+12%",
        direction: "up",
        positiveIsGood: true,
      },
      {
        id: "rm-2",
        label: "Estimated reach",
        value: "48.6M",
        delta: "+9%",
        direction: "up",
        positiveIsGood: true,
      },
      {
        id: "rm-3",
        label: "Positive sentiment",
        value: "58%",
        delta: "+3 pts",
        direction: "up",
        positiveIsGood: true,
      },
      {
        id: "rm-4",
        label: "Tier 1 placements",
        value: "204",
        delta: "-6%",
        direction: "down",
        positiveIsGood: true,
      },
    ],
  },
  {
    id: "r-p-chart",
    kind: "barChart",
    sectionId: "sec-performance",
    title: "Placements by day",
    points: COVERAGE_TREND,
  },
  {
    id: "r-t-title",
    kind: "sectionTitle",
    title: "Narrative Themes",
    sectionId: "sec-themes",
  },
  {
    id: "r-t-summary",
    kind: "summary",
    sectionId: "sec-themes",
    text: "Portfolio execution overtook pricing as the dominant theme for the first time in six weeks, carried almost entirely by earnings coverage. Access and affordability held steady in third position but is the theme most likely to strengthen given the hearing calendar.",
  },
  {
    id: "r-t-table",
    kind: "table",
    sectionId: "sec-themes",
    columns: ["Theme", "Placements", "Sentiment", "Trajectory"],
    rows: [
      { cells: ["Portfolio execution", "342", "78% positive", "Strengthening"] },
      { cells: ["Pricing & policy", "289", "34% positive", "Holding"] },
      { cells: ["Access & affordability", "198", "41% positive", "Strengthening"] },
      { cells: ["R&D pipeline", "164", "82% positive", "Holding"] },
      { cells: ["Manufacturing & supply", "114", "66% positive", "Fading"] },
    ],
  },
  {
    id: "r-c-title",
    kind: "sectionTitle",
    title: "Top Coverage",
    sectionId: "sec-top-coverage",
  },
  {
    id: "r-c-stories",
    kind: "stories",
    sectionId: "sec-top-coverage",
    articles: getArticles([
      "art-manufacturing",
      "art-q2-revenue",
      "art-esg-report",
    ]),
  },
  {
    id: "r-footer",
    kind: "footer",
    text: "Generated by Herald for Pfizer Corporate Reputation. Coverage sourced from Handraise media intelligence.",
  },
];

/* -------------------------------------------------------------------------- */

const EDITION_BLOCKS_BY_TEMPLATE: Record<string, EditionBlock[]> = {
  "tpl-morning-brief": MORNING_BLOCKS,
  "tpl-exec-summary": EXEC_BLOCKS,
  "tpl-competitive": COMPETITIVE_BLOCKS,
  "tpl-coverage-report": REPORT_BLOCKS,
};

/** Deep-clones blocks so each briefing owns an independently editable edition. */
function cloneBlocks(blocks: EditionBlock[], suffix: string): EditionBlock[] {
  return blocks.map((b) => ({
    ...structuredClone(b),
    id: `${b.id}-${suffix}`,
  })) as EditionBlock[];
}

/**
 * Builds the generated edition for a briefing. Templates without hand-authored
 * content fall back to a structure derived from the template's own blocks, so
 * every template can still produce a credible edition.
 */
export function buildEdition(
  briefingId: string,
  templateId: string,
  opts: {
    dateLabel: string;
    windowLabel: string;
    /**
     * Template to derive structure from when it is not in the static list —
     * used for drafts being composed in Herald's template creation flow.
     */
    template?: Template;
  },
): Edition {
  const authored = EDITION_BLOCKS_BY_TEMPLATE[templateId];
  const template = opts.template ?? getTemplate(templateId);

  const blocks = authored
    ? cloneBlocks(authored, briefingId)
    : buildFallbackBlocks(briefingId, template);

  return {
    id: `ed-${briefingId}`,
    briefingId,
    dateLabel: opts.dateLabel,
    windowLabel: opts.windowLabel,
    articlesScanned: 1284,
    blocks,
  };
}

/**
 * Derives an edition from a template's block list. Used for templates created
 * through Herald during the session, which have no authored content.
 */
function buildFallbackBlocks(
  briefingId: string,
  template: Template | undefined,
): EditionBlock[] {
  if (!template) return [];

  const pool = [
    "art-q2-revenue",
    "art-oncology-pipeline",
    "art-manufacturing",
    "art-pricing-hearing",
    "art-eu-access",
    "art-competitor-launch",
    "art-esg-report",
    "art-clinical-diversity",
    "art-supply-chain",
  ];
  let cursor = 0;
  const take = (n: number) => {
    const ids = pool.slice(cursor, cursor + n);
    cursor = (cursor + n) % pool.length;
    return getArticles(ids.length ? ids : pool.slice(0, n));
  };

  const blocks: EditionBlock[] = [];

  for (const b of template.blocks) {
    const id = `${b.id}-${briefingId}`;
    const sectionId = b.sectionId ?? "";
    const sectionTitle =
      template.sections.find((s) => s.id === sectionId)?.title ?? "Section";

    switch (b.kind) {
      case "banner":
        blocks.push({
          id,
          kind: "banner",
          title: template.name,
          subtitle: "Global Communications",
        });
        break;
      case "contents":
        blocks.push({
          id,
          kind: "contents",
          entries: template.sections.map((s) => ({ id: s.id, title: s.title })),
        });
        break;
      case "sectionTitle":
        blocks.push({ id, kind: "sectionTitle", title: sectionTitle, sectionId });
        break;
      case "summary":
        blocks.push({
          id,
          kind: "summary",
          sectionId,
          text: `Coverage in this section is drawn from the instruction set on this briefing. Herald selected the placements below from 1,284 articles in the lookback window and ordered them by likely impact on ${sectionTitle.toLowerCase()}.`,
        });
        break;
      case "metrics":
        blocks.push({ id, kind: "metrics", sectionId, metrics: METRICS_EXEC });
        break;
      case "stories":
        blocks.push({ id, kind: "stories", sectionId, articles: take(3) });
        break;
      case "table":
        blocks.push({
          id,
          kind: "table",
          sectionId,
          columns: ["Theme", "Placements", "Sentiment", "Trajectory"],
          rows: [
            { cells: ["Portfolio execution", "342", "78% positive", "Strengthening"] },
            { cells: ["Pricing & policy", "289", "34% positive", "Holding"] },
            { cells: ["R&D pipeline", "164", "82% positive", "Holding"] },
          ],
        });
        break;
      case "barChart":
      case "lineChart":
        blocks.push({
          id,
          kind: b.kind,
          sectionId,
          title: b.label,
          points: COVERAGE_TREND,
        });
        break;
      case "pieChart":
        blocks.push({
          id,
          kind: "pieChart",
          sectionId,
          title: b.label,
          points: [
            { label: "Pfizer", value: 34 },
            { label: "Competitor A", value: 27 },
            { label: "Competitor B", value: 21 },
            { label: "Competitor C", value: 11 },
            { label: "Others", value: 7 },
          ],
        });
        break;
      case "callout":
        blocks.push({
          id,
          kind: "callout",
          sectionId,
          tone: "note",
          title: "Watch item",
          text: "Herald flags this as the item most likely to require a decision before the next edition.",
        });
        break;
      case "quote":
        blocks.push({
          id,
          kind: "quote",
          sectionId,
          text: "The company's position was represented accurately in seven of nine placements, with two outlets quoting only the first half of the statement.",
          attribution: "Herald analysis of coverage in the lookback window",
        });
        break;
      case "divider":
        blocks.push({ id, kind: "divider" });
        break;
      case "footer":
        blocks.push({
          id,
          kind: "footer",
          text: "Generated by Herald for Pfizer Global Communications. Coverage sourced from Handraise media intelligence.",
        });
        break;
      default:
        break;
    }
  }

  return blocks;
}
